export * from './fill-profile-geoposition.input.js'
export * from './fill-profile-gender.input.js'
export * from './fill-profile-name.input.js'
export * from './add-profile-photo.input.js'
export * from './skip-profile.input.js'
export * from './like-profile.input.js'
