enableGlobalCache: false

pnpIgnorePatterns:
  - ./native/**

pnpEnableEsmLoader: true

packageExtensions:
  '@monstrs/protobuf-rpc@*':
    dependencies:
      '@bufbuild/protobuf': '*'
  '@nestjs/microservices@*':
    dependencies:
      '@grpc/grpc-js': '*'
      '@grpc/proto-loader': '*'
      ioredis: '*'
      kafkajs: '*'
  '@nestjs/websockets@*':
    dependencies:
      '@nestjs/platform-socket.io': '*'
  '@nestjs/apollo@*':
    dependencies:
      '@as-integrations/fastify': '*'
  nestjs-dataloader@*:
    peerDependencies:
      '@nestjs/common': '*'
      '@nestjs/core': '*'
      '@nestjs/graphql': '*'
      graphql: '*'
  knex@*:
    dependencies:
      pg: '*'
      pg-query-stream: '*'
      tedious: '*'

yarnPath: .yarn/releases/yarn-remote.cjs
